version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql    #データの永続化のために必要
    ports:
      - "3306:3306"

  rails:
    build: .
    command: >
      bash -c 'rm -f /rails_app/tmp/pids/server.pid && bundle install &&
      bundle exec rails s -p 3000 -b '0.0.0.0''
    volumes:
      - .:/rails_app
    ports:
      - "3000:3000"
    links:
      - db
  
volumes:
  mysql: